# Generated by Django 3.0.5 on 2020-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
