# Generated by Django 3.0.5 on 2020-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_order_date_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivered',
            field=models.DateTimeField(null=True),
        ),
    ]
